# Generated by Django 6.0.4 on 2026-05-05 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='NatureGenetique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Nature Génétique',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='TypeRessource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Type de Ressource',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='NomRessource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ressources_noms', to='ressources_genetiques.categorie')),
            ],
            options={
                'verbose_name': 'Nom de la Ressource',
                'ordering': ['nom'],
                'unique_together': {('categorie', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='Espece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('nom_ressource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especes', to='ressources_genetiques.nomressource')),
            ],
            options={
                'verbose_name': 'Espèce',
                'ordering': ['nom'],
                'unique_together': {('nom_ressource', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='RessourceGenetique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denomination', models.CharField(max_length=150, verbose_name='Dénomination')),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ressources_genetiques.categorie', verbose_name='Catégorie')),
                ('espece', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ressources_genetiques.espece', verbose_name='Espèce')),
                ('nature_genetique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ressources_genetiques.naturegenetique', verbose_name='Nature génétique')),
                ('nom_ressource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ressources_genetiques.nomressource', verbose_name='Ressource génétique')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('type_ressource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ressources_genetiques.typeressource', verbose_name='Type de ressource')),
            ],
            options={
                'verbose_name': 'Ressource Génétique',
                'verbose_name_plural': 'Ressources Génétiques',
                'ordering': ['-date_enregistrement'],
            },
        ),
        migrations.AddField(
            model_name='categorie',
            name='type_ressource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='ressources_genetiques.typeressource'),
        ),
        migrations.AlterUniqueTogether(
            name='categorie',
            unique_together={('type_ressource', 'nom')},
        ),
    ]
